language: cpp
compiler:
  - clang
  - gcc

dist: trusty
sudo: false

os:
  - osx
  - linux

addons:
  apt:
    sources:
      - sourceline: 'ppa:ubuntu-toolchain-r/test'
    packages:
      - libc++1
      - libc++-dev
      - g++-4.9

script:
  - if [ "$TRAVIS_OS_NAME" != "osx" -a "$CXX" = "g++" ]; then export CXX="g++-4.9"; fi
  - make test CFLAGS="-O2 -coverage" CXX=${CXX}
